name: Build and deploy Node.js app to Azure Web App - tixe-backend-app-service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js (match your package.json)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: backend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run tests (optional)
        working-directory: backend
        run: |
          if [ -f package.json ]; then
            npm run test --if-present || echo "Tests failed or not present, continuing..."
          fi

      - name: Archive backend for deployment
        run: |
          cd backend
          zip -r ../backend-deploy.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: tixe-backend-app-service
          package: ./backend-deploy.zip
