name: Build & deploy Node.js backend to Azure Web App - tixe-backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: backend
        run: |
          npm install

      - name: Archive backend for deployment
        run: |
          cd backend
          zip -r ../backend-deploy.zip .

      - name: Deploy to Azure Web App via publish profile
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          app-name: tixe-backend
          package: ./backend-deploy.zip

      
