name: Build & deploy Node.js backend to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: backend
        run: |
          npm install

      - name: Archive backend for deployment
        run: |
          cd backend
          zip -r ../backend-deploy.zip .

      - name: Deploy to Azure Web App via publish profile
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          app-name: tixe-backend-app-service
          package: ./backend-deploy.zip

      - name: Post-deploy health check
        run: |
          echo "Waiting for app to warm up..."
          sleep 8
          URL="https://tixe-backend-app-service.azurewebsites.net/health"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          if [ "$STATUS" != "200" ]; then
            echo "Health check failed: HTTP $STATUS at $URL"
            exit 1
          else
            echo "Health check passed."
          fi
